version: 0.2

phases:
  install:
    runtime-version:
      docker: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Executing Build Phase
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - Dockerrun.aws.json
    - ./docker/Dockerfile
    - ./src/**/*
    - ./config/*
