version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    pre_build:
      commands:
        - echo pre-build nodejs backend
    build:
      commands:
        - echo build nodejs backend
        # Build the Docker images
        - echo Building the production docker image
        - docker build -t nlcd/admission .
    post_build:
      commands:
        - echo post building docker image
        - docker push nlcd/admission
artifacts:
  files:
    - '**/*'
