version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    pre_build:
      commands:
        - echo PRE_BUILD Phase
    build:
      commands:
        - npm install
    post_build:
      commands:
        - echo POST_BUILD Phase
artifacts:
  files:
    - package.json
    - package-lock.json
    - 'config/*'
    - 'src/*'
    - 'src/**/*'
    - Dockerfile
    - docker-compose.yml
