version: 0.2

phases:
  install:
    runtime-version:
      docker: 20
  pre_build:
    commands:
      - npm install
      - npm ci && npm cache clean --force
  build:
    commands:
      - npm start
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - Dockerfile
