version: '3.7'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run start
    environment:
      PORT: 3000
      MONGO_URL: 'mongodb+srv://admin:admin123@cluster0.auvyu.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
      NODE_ENV: 'development'
    networks:
      - common

  mongo:
    image: mongo
    volumes:
      - ./mongodb/data/db
    ports:
      - '27017:27017'
    networks:
      - common

networks:
  common:
