version: '3.7'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    command: npm run start
    environment:
      PORT: 80
      mongoDB: mongodb+srv://admin:admin123@cluster0.auvyu.mongodb.net/Admission_University?retryWrites=true&w=majority
      NODE_ENV: 'production'
