version: '3'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
    command: npm run start
    environment:
      PORT: 3000
      mongoDB: mongodb+srv://admin:admin123@cluster0.auvyu.mongodb.net/Admission_University?retryWrites=true&w=majority
      NODE_ENV: 'production'
    networks:
      - common

  mongo:
    container_name: mongoDB
    image: mongo
    volumes:
      - ./data:/data/dbconnection
    ports:
      - 27017:27017
    networks:
      - common

networks:
  common:
