version: '3.3'

services:
  node_server:
    container_name: node_server
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    # - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - ./config/.env
