# Version
openapi: 3.0.0

# Information about Swagger
info:
  title: Swagger API for Admission University
  description: This is swagger api documentation made by TDM team
  version: 1.0.0
  contact:
    email: danhnlcse140655@fpt.edu.vn
  servers:
    -url: http://localhost:3000/
    description: This is my local server
    -url: http://nodejs-backend3.us-east-2.elasticbeanstalk.com/
    description: This is my production server

# Paths
paths:
  /api/v1/regions:
    get:
      summary: Returns a object include code and list regions.
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of region information
          content:
            application/json:
              schema: 
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                    example: 200
                  data:
                    type: array
                    example: []

  /api/v1/schools:
    get:
      summary: Returns a object include code and list schools.
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of school information
          content:
            application/json:
              schema: 
                type: object
                properties:
                  code:
                    type: integer
                    format: int64
                    example: 200
                  data:
                    type: array
                    example: []

  /api/v1/users:
    get:
      summary: Returns a object include code and list users.
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of user information
          content:
            application/json:
              schema: 
                type: array
                example: []

  /api/v1//users/{username}:
    get:
      summary: Returns a user by username.
      parameters:
        - name: username
          in: path
          required: true
          description: The useraname of the user to return.
          schema:
            type: string
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: The specified username is invalid.
        '404':
          description: A user with the specified username was not found.
        default:
          description: Unexpected error

  /api/v1/users:
    post:
      summary: Creates a user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses: 
        '201':
          description: Created

  /api/v1/users/login:
    post:
      summary: Login feature.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses: 
        '201':
          description: Created

  /api/v1//users/{username}:
    put:
      summary: User will be update.
      parameters:
        - name: username
          in: path
          required: true
          description: Delete user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: A object.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: The specified username is invalid.
        '404':
          description: A user with the specified username was not found.
        default:
          description: Unexpected error

  /api/v1//users/{username}:
    delete:
      summary: User will be deleted.
      parameters:
        - name: username
          in: path
          required: true
          description: Delete user.
          schema:
            type: string
      responses:
        '200':
          description: A object.
          content:
            application/json:
              schema:
                type: object
        '400':
          description: The specified username is invalid.
        '404':
          description: A user with the specified username was not found.
        default:
          description: Unexpected error